### PR TITLE
New York Times review

### PR DESCRIPTION
**Pull request by ashraffares**
- added article section
 -Centerd the nav bar logo
-add live link to readme file

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @ashraffares**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] please fix all of your linters issues.
- [x] please make sure your Pull request has a descriptive description.
- [ ] your project should have a professional readme file.

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @ashraffares 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes 👇.
- [ ] Please add a descriptive README.md and PR description([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

**Hints:**
1. Read and understand about PR. Please Visit for [PR](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
2. Please visit for the README [template](https://github.com/microverseinc/readme-template)

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi  @ashraffares, I am Abdulaziz Redi Ali, your TSE for this PR.  👏👏  I appreciate your hard work in replicating nytimes.com.   Kindly fix the following issues.

[REQUIRED]

- [x] Fix the Elements inside the main content, All elements should be centered
- [x] Add the "Most popular" section and the "suggested newsletters" section on the bottom part of the page as on the original site
- [x] Remove the "Contact with us" section as it doesn't appear on the original page
- [x] Fx  the bottom section of the page similar to the original site

| Your Copy | Source | 
| :---:         |     :---:      |
| nycopy |nyoriginal |

- [ ] Fix the readme file by adding more relevant content and add a live link

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @ashraffares  
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes 👇.
- [ ] Please add a descriptive README.md and PR description([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] Fix the Elements inside the main content, All elements should be centered

### Navbar
- [ ] Manage the alignment
- [ ] Add the logo with navigation link

|[Source Page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|[Clone Page](https://ashraffares.github.io/the-new-york-times-site/)|
|:---:|:---:|
|source-page|clone|


**Hints:**
1. Read and understand about PR. Please Visit for [PR](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
2. Please visit for the README [template](https://github.com/microverseinc/readme-template)



##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by ashraffares** [comment]
so there is no problem with the site on my local machine when I  try to
push the code it's not displaying on GitHub but on my local
machine everything looks fine so what should I do?

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team    
#### Great Job so far, everything works fine, but there is a minor change. 
### General 
- [ ] Lets format the readme.MD file properly.
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] Please add the description in Pull Request.
- [ ] Please add a proper description of the project in the README file
- [ ] Please explain Prerequisites, Setup, Install, Usage, Run, Deployment
- [ ] Please remove tests from the README file
- [ ] There is a 404 Error(Page is not found) by clicking on MIT in the readme, Please fix this issue.
### Hint
Changes are based on General Requirements, Please read the general requirments.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
**To the point Hints**
1. Read and understand about PR. Please Visit for [PR](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
2. Please visit for the README [template](https://github.com/microverseinc/readme-template)


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by layzrd — APPROVED** [review]
### Status: Approved 🙌 🎇
Hi @ashraffares and @billodiallo, I am  [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  Congratulations 🎊 👏, you did very well on this project.

Now, you can move ahead.

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Review by PhillipUg — APPROVED** [review]
# Status: Project Approved! 🥇 
Congratulations on implementing all requirements and getting this project approved. :+1:

You can merge this branch into the main branch when you're ready and go on to your next project.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime**

**Pull request merged**
